In [1]:
import pandas as pd
import yfinance as yf

In [2]:
help(yf.Ticker)

Help on class Ticker in module yfinance.ticker:

class Ticker(yfinance.base.TickerBase)
 |  Ticker(ticker, session=None)
 |
 |  Method resolution order:
 |      Ticker
 |      yfinance.base.TickerBase
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, ticker, session=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  option_chain(self, date=None, proxy=None, tz=None)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  actions
 |
 |  analyst_price_target
 |
 |  balance_sheet
 |
 |  balancesheet
 |
 |  calendar
 |
 |  capital_gains
 |
 |  cash_flow
 |
 |  cashflow
 |
 |  dividends
 |
 |  earnings
 |
 |  earnings_dates
 |
 |  earnings_forecasts
 |
 |  earnings_trend
 |
 |  fast_info
 |
 |  financials
 |
 |  history_metadata
 |
 |  income_stmt
 |
 |  incomestmt
 |
 |  info
 |
 |  institutional_holders
 |
 |  isin
 |
 |  major_holders
 |
 |  mutualfund_holders
 |
 |  news
 |
 |  options
 |
 |  quarterly_balance_sheet
 |
 |  quarterly_balancesheet
 |
 |  quarterly_cash_flow
 |
 |  quarterly_cashflow
 |
 |  quarterly_earnings
 |
 |  quarterly_financials
 |
 |  quarterly_income_stmt
 |
 |  quarterly_incomestmt
 |
 |  recommendations
 |
 |  recommendations_summary
 |
 |  revenue_forecasts
 |
 |  shares
 |
 |  splits
 |
 |  sustainability
 |
 |  trend_details
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from yfinance.base.TickerBase:
 |
 |  get_actions(self, proxy=None)
 |
 |  get_analyst_price_target(self, proxy=None, as_dict=False)
 |
 |  get_balance_sheet(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_balancesheet(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_calendar(self, proxy=None, as_dict=False)
 |
 |  get_capital_gains(self, proxy=None)
 |
 |  get_cash_flow(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_cashflow(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_dividends(self, proxy=None)
 |
 |  get_earnings(self, proxy=None, as_dict=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_earnings_dates = wrapper(*args, **kwargs)
 |
 |  get_earnings_forecast(self, proxy=None, as_dict=False)
 |
 |  get_earnings_trend(self, proxy=None, as_dict=False)
 |
 |  get_fast_info(self, proxy=None)
 |
 |  get_financials(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_history_metadata(self, proxy=None) -> dict
 |
 |  get_income_stmt(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_incomestmt(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_info(self, proxy=None) -> dict
 |
 |  get_institutional_holders(self, proxy=None, as_dict=False)
 |
 |  get_isin(self, proxy=None) -> Optional[str]
 |
 |  get_major_holders(self, proxy=None, as_dict=False)
 |
 |  get_mutualfund_holders(self, proxy=None, as_dict=False)
 |
 |  get_news(self, proxy=None)
 |
 |  get_recommendations(self, proxy=None, as_dict=False)
 |
 |  get_recommendations_summary(self, proxy=None, as_dict=False)
 |
 |  get_rev_forecast(self, proxy=None, as_dict=False)
 |
 |  get_shares(self, proxy=None, as_dict=False)
 |
 |  get_shares_full = wrapper(*args, **kwargs)
 |
 |  get_splits(self, proxy=None)
 |
 |  get_sustainability(self, proxy=None, as_dict=False)
 |
 |  get_trend_details(self, proxy=None, as_dict=False)
 |
 |  history = wrapper(*args, **kwargs)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from yfinance.base.TickerBase:
 |
 |  basic_info
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from yfinance.base.TickerBase:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [3]:
data = yf.download(["GOOG","KPITTECH.NS"], period="5Y")
data

[*********************100%%**********************]  2 of 2 completed

             Adj Close                    Close                     High  \
                  GOOG  KPITTECH.NS        GOOG  KPITTECH.NS        GOOG
Date
2019-01-07   53.419498          NaN   53.419498          NaN   53.700001
2019-01-08   53.813999          NaN   53.813999          NaN   54.228001
2019-01-09   53.733002          NaN   53.733002          NaN   54.131500
2019-01-10   53.516499          NaN   53.516499          NaN   53.557499
2019-01-11   52.859501          NaN   52.859501          NaN   53.188751
...                ...          ...         ...          ...         ...
2024-01-01         NaN  1490.500000         NaN  1490.500000         NaN
2024-01-02  139.559998  1467.849976  139.559998  1467.849976  140.615005
2024-01-03  140.360001  1462.699951  140.360001  1462.699951  141.089996
2024-01-04  138.039993  1472.400024  138.039993  1472.400024  140.634995
2024-01-05  137.389999  1506.550049  137.389999  1506.550049  138.809998

                                Low                     Open               \
            KPITTECH.NS        GOOG  KPITTECH.NS        GOOG  KPITTECH.NS
Date
2019-01-07          NaN   52.737999          NaN   53.575001          NaN
2019-01-08          NaN   53.026501          NaN   53.805500          NaN
2019-01-09          NaN   53.320000          NaN   54.082500          NaN
2019-01-10          NaN   52.885502          NaN   53.382999          NaN
2019-01-11          NaN   52.424000          NaN   53.159000          NaN
...                 ...         ...          ...         ...          ...
2024-01-01  1515.900024         NaN  1488.250000         NaN  1513.849976
2024-01-02  1498.500000  137.740005  1458.599976  139.600006  1498.449951
2024-01-03  1488.699951  138.429993  1455.099976  138.600006  1472.900024
2024-01-04  1485.000000  138.009995  1459.000000  139.850006  1460.000000
2024-01-05  1509.000000  136.850006  1470.900024  138.352005  1479.000000

                Volume
                  GOOG KPITTECH.NS
Date
2019-01-07  39638000.0         NaN
2019-01-08  35298000.0         NaN
2019-01-09  23986000.0         NaN
2019-01-10  29128000.0         NaN
2019-01-11  30416000.0         NaN
...                ...         ...
2024-01-01         NaN    813082.0
2024-01-02  20071900.0    912412.0
2024-01-03  18974300.0    645767.0
2024-01-04  18253300.0    702692.0
2024-01-05  15433200.0    920923.0

[1295 rows x 12 columns]

In [4]:
data.shape

(1295, 12)

In [5]:
data.xs("GOOG", level=1, axis=1)

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2019-01-07,53.419498,53.419498,53.700001,52.737999,53.575001,39638000.0
2019-01-08,53.813999,53.813999,54.228001,53.026501,53.805500,35298000.0
2019-01-09,53.733002,53.733002,54.131500,53.320000,54.082500,23986000.0
2019-01-10,53.516499,53.516499,53.557499,52.885502,53.382999,29128000.0
2019-01-11,52.859501,52.859501,53.188751,52.424000,53.159000,30416000.0
...,...,...,...,...,...,...
2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-02,139.559998,139.559998,140.615005,137.740005,139.600006,20071900.0
2024-01-03,140.360001,140.360001,141.089996,138.429993,138.600006,18974300.0
2024-01-04,138.039993,138.039993,140.634995,138.009995,139.850006,18253300.0
2024-01-05,137.389999,137.389999,138.809998,136.850006,138.352005,15433200.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1295 entries, 2019-01-07 to 2024-01-05
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (Adj Close, GOOG)         1259 non-null   float64
 1   (Adj Close, KPITTECH.NS)  1167 non-null   float64
 2   (Close, GOOG)             1259 non-null   float64
 3   (Close, KPITTECH.NS)      1167 non-null   float64
 4   (High, GOOG)              1259 non-null   float64
 5   (High, KPITTECH.NS)       1167 non-null   float64
 6   (Low, GOOG)               1259 non-null   float64
 7   (Low, KPITTECH.NS)        1167 non-null   float64
 8   (Open, GOOG)              1259 non-null   float64
 9   (Open, KPITTECH.NS)       1167 non-null   float64
 10  (Volume, GOOG)            1259 non-null   float64
 11  (Volume, KPITTECH.NS)     1167 non-null   float64
dtypes: float64(12)
memory usage: 131.5 KB